language: r

sudo: false

r_packages:
  - qcc

r_github_packages:
  - rstudio/bookdown

script:
  - ./build.sh
  - ./deploy.sh

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_book/_bookdown_files
